### ISSUE TITLE
private_registries not working

### ISSUE THREAD

**Issue by insekticid** [yamamoto-febc/terraform-provider-rke#25]
What I am doing wrong?

```
  private_registries = {
    url      = "xxx"
    user     = "xxx"
    password = "xxx"
  }
```

![image](https://user-images.githubusercontent.com/177340/44338870-af152300-a47f-11e8-8357-7e5e03eeb7df.png)

**Comment by yamamoto-febc** [comment]
Hi @insekticid,
  
RKE's private registry and Rancher's private registry are different.

RKE's private registry setting is used when deploying kubernetes by RKE.
On the other hand, Rancher UI's private registry setting is used when creating the k8s workload from Rancher.

Therefore, even if `private_registries` is set in RKE, it will not be displayed in Rancher.

**Comment by insekticid** [comment]
@yamamoto-febc ok, solved with

```
kubectl -n cattle-system create secret docker-registry regcred \
  --docker-server="registry.example.com" \
  --docker-email=registry@example.com \
  --docker-username=name \
  --docker-password=password
```

or

```
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6Im5hbWUiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiZW1haWwiOiJyZWdpc3RyeUBleGFtcGxlLmNvbSIsImF1dGgiOiJibUZ0WlRwd1lYTnpkMjl5WkE9PSJ9fX0=
kind: Secret
metadata:
  name: gitlab
  namespace: kube-system
type: kubernetes.io/dockerconfigjson
```

where .dockerconfigjson is base64
```
{"auths":{"registry.example.com":{"username":"name","password":"password","email":"registry@example.com","auth":"bmFtZTpwYXNzd29yZA=="}}}
```

where auth is base64
```
name:password
```

https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#private-registry
