### ISSUE TITLE
Recurring Snapshots not working

### ISSUE THREAD

**Issue by azelezni** [yamamoto-febc/terraform-provider-rke#97]
When configuring ETCD S3 snapshots, the cluster is provisioned correctly but the snapshots never start, I have to trigger them manually.
```
services_etcd {
    backup_config {
      interval_hours = 1
      retention = 6
      s3_backup_config {
        access_key = aws_iam_access_key.etcd_backup.id
        secret_key = aws_iam_access_key.etcd_backup.secret
        bucket_name = aws_s3_bucket.etcd_backup.bucket
        region = aws_s3_bucket.etcd_backup.region
        endpoint = "s3.amazonaws.com"
      }
    }
  }
```
When I check `cluster.yaml` I see that `backup_config` has `enabled: null`, trying to add `enabled: true` in the resource just gives an error.
```
backup_config:
      enabled: null
      interval_hours: 1
      retention: 6
      s3backupconfig:
        access_key: <access_key>
        secret_key: <secret_key>
        bucket_name: <bucket_name>
        region: us-east-1
        endpoint: s3.amazonaws.com
```
